settings:
  default_reset_button_label: Palauta
  default_delete_button_label: Poista
  default_preview_next_button_label: Preview
  default_preview_label: Preview
element:
  default_more_title: Lisää
