settings:
  default_reset_button_label: Réinitialiser
  default_delete_button_label: Supprimer
  default_preview_next_button_label: Preview
  default_preview_label: Preview
element:
  default_more_title: More
