_core:
  default_config_hash: PipyKPJHaHaJB3D4LeRoRJxSSd7QbBM0gb5wpSrEFfc
ignored_config_entities:
  - 'eu_cookie_compliance.cookie_category*'
  - 'next.*'
  - simple_oauth.settings
  - elasticsearch_connector.cluster.infofinland
  - update.settings
