max_links: 4000
cron_generate: true
cron_generate_interval: 3
generate_duration: 10000
remove_duplicates: true
skip_untranslated: true
disable_language_hreflang: false
xsl: false
base_url: 'https://edit.infofinland.fi'
default_variant: ''
custom_links_include_images: false
excluded_languages: {  }
enabled_entity_types:
  - node
  - taxonomy_term
  - menu_link_content
entities_per_queue_item: 50
