settings:
  default_reset_button_label: Tühista
  default_delete_button_label: Kustuta
  default_preview_next_button_label: Preview
  default_preview_label: Preview
element:
  default_more_title: Veel
